# Generated by Django 4.2.5 on 2023-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='rating',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='reviews',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='main',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
