# Generated by Django 4.2.5 on 2023-09-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_main_rating_main_reviews_alter_main_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='item_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='kelas',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='npm',
            field=models.IntegerField(default=0),
        ),
    ]
