# Generated by Django 4.2.5 on 2023-09-19 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_main_item_name_main_kelas_main_npm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_img/')),
                ('amount', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('rating', models.CharField(max_length=4)),
                ('reviews', models.TextField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='main',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='main',
            name='description',
        ),
        migrations.RemoveField(
            model_name='main',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='main',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='main',
            name='reviews',
        ),
    ]
