# Generated by Django 4.2.5 on 2023-09-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_remove_main_amount_remove_main_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='describe the product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products_img/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.TextField(default='type your review here'),
        ),
    ]
