# Generated by Django 4.2.5 on 2023-09-26 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_remove_product_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='name',
        ),
        migrations.AddField(
            model_name='main',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
