# Generated by Django 4.2.5 on 2023-09-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_main_user_main_name_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='name',
        ),
    ]
